# Generated by Django 4.2.4 on 2024-04-26 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTNAPIUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250)),
                ('wallet_balance', models.FloatField()),
                ('key', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='APIUsersHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intel_app.mtnapiusers')),
                ('mtn_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intel_app.mtntransaction')),
            ],
        ),
    ]
