# Generated by Django 4.2.4 on 2024-04-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0002_mtnapiusers_apiusershistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIMTNBundlePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('bundle_volume', models.FloatField()),
            ],
        ),
    ]
