# Generated by Django 4.2.4 on 2024-05-04 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0006_alter_category_image_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=250, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_use', models.CharField(blank=True, max_length=250, null=True)),
                ('transaction_amount', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
