# Generated by Django 4.2.4 on 2024-05-04 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0007_wallettransactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WalletTransactions',
            new_name='WalletTransaction',
        ),
    ]
