# Generated by Django 4.2.4 on 2024-05-10 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import intel_app.custom_storages


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0009_wallettransaction_new_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=intel_app.custom_storages.MediaStorage(), upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=intel_app.custom_storages.MediaStorage(), upload_to='product_images/'),
        ),
        migrations.CreateModel(
            name='ApiWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=250, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_amount', models.FloatField()),
                ('new_balance', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
