# Generated by Django 4.2.4 on 2024-05-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0011_admininfo_sign_up_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='data_bundle_access',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
