# Generated by Django 4.2.4 on 2023-11-16 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0011_agentisharebundleprice_agentmtnbundleprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='momo_numberr',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admininfo',
            name='payment_channell',
            field=models.CharField(choices=[('MTN Mobile Money', 'MTN Mobile Money'), ('Vodafone Cash', 'Vodafone Cash'), ('AT Money', 'AT Money')], default='mtn', max_length=250),
            preserve_default=False,
        ),
    ]
