# Generated by Django 4.2.4 on 2024-05-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0012_customuser_data_bundle_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='afa_super_agent_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
