# Generated by Django 4.2.4 on 2024-05-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0013_admininfo_afa_super_agent_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='agent_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
