# Generated by Django 5.0 on 2024-06-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0016_agentvodabundleprice_superagentvodabundleprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='payment_active',
            field=models.BooleanField(default=True),
        ),
    ]
