# Generated by Django 4.2.4 on 2024-07-18 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0017_admininfo_payment_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='APITelecelBundlePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('bundle_volume', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='apiwallettransaction',
            name='transaction_channel',
            field=models.CharField(blank=True, choices=[('MTN', 'MTN'), ('Telecel', 'Telecel')], default='MTN', max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='TelecelAPIUsersHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intel_app.mtnapiusers')),
                ('telecel_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intel_app.vodafonetransaction')),
            ],
        ),
    ]
