# Generated by Django 4.2.4 on 2024-08-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0019_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtntransaction',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
