# Generated by Django 4.2.4 on 2024-08-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0021_profitinstance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitinstance',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
