# Generated by Django 4.2.4 on 2024-10-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0023_generatedwallettotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='vodafonetransaction',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
