# Generated by Django 4.2.4 on 2024-10-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0024_vodafonetransaction_amount'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mtntransaction',
            index=models.Index(fields=['bundle_number', 'transaction_status'], name='intel_app_m_bundle__060fce_idx'),
        ),
    ]
