# Generated by Django 4.2.4 on 2024-10-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0025_mtntransaction_intel_app_m_bundle__060fce_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtntransaction',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vodafonetransaction',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
